name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      instanceName:
        description: 'Name of the instance'
        required: true
        default: 'default-instance'
      awsRegion:
        description: 'AWS region to deploy resources'
        required: true
        default: 'us-east-1'
      instanceType:
        description: 'Type of instance'
        required: true
        default: 't2.micro'
      action:
        description: 'Action to perform'
        required: false
        default: 'apply'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ github.event.inputs.awsRegion || 'us-east-1' }}
      AMI: ${{ github.event.inputs.ami || 'ami-04a81a99f5ec58529' }}
      INSTANCE_TYPE: ${{ github.event.inputs.instanceType || 't2.micro' }}
      INSTANCE_NAME: ${{ github.event.inputs.instanceName || 'default-instance' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: |
        terraform plan \
          -var "aws_region=${{ env.AWS_REGION }}" \
          -var "ami=${{ env.AMI }}" \
          -var "instance_type=${{ env.INSTANCE_TYPE }}" \
          -var "instance_name=${{ env.INSTANCE_NAME }}"

    - name: Terraform Apply
      if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply') }}
      run: |
        terraform apply -auto-approve \
          -var "aws_region=${{ env.AWS_REGION }}" \
          -var "ami=${{ env.AMI }}" \
          -var "instance_type=${{ env.INSTANCE_TYPE }}" \
          -var "instance_name=${{ env.INSTANCE_NAME }}"
